// testers/routes/src/entry.client.tsx
import { initClient } from "@hwy-js/client";
import { RootOutlet } from "hwy";
import React, { startTransition } from "react";
import { hydrateRoot } from "react-dom/client";

await initClient(() => {
  startTransition(() => {
    hydrateRoot(
      document.querySelector("main") as HTMLElement,
      <React.StrictMode>
        <RootOutlet
          fallbackErrorBoundary={function ErrorBoundary() {
            return <div>Error Boundary in Root</div>;
          }}
        />
      </React.StrictMode>,
    );
  });
});

// projects/testers/routes-lit/entry.client.ts
import { initClient } from "@hwy-js/client";
import { HwyRootOutlet } from "@hwy-js/lit";
import { html, render } from "lit";
import { Sidebar } from "./components/sidebar";

await initClient(() => {
  render(
    html`
      ${Sidebar({})}
      <main>
        ${HwyRootOutlet({
          fallbackErrorBoundary: () => html`<div>Error Boundary in Root</div>`,
        })}
      </main>
    `,
    document.getElementById("root") as HTMLElement,
  );
});
