// docs/src/entry.client.tsx
import { initClient } from "@hwy-js/client";
import { RootOutlet } from "hwy";
import React from "react";
import { hydrateRoot } from "react-dom/client";
import { RootLayout } from "./pages/layout.js";

await initClient(() => {
  hydrateRoot(
    document.getElementById("root") as HTMLElement,
    <React.StrictMode>
      <RootOutlet
        fallbackErrorBoundary={() => <div>Something went wrong.</div>}
        layout={RootLayout}
      />
    </React.StrictMode>,
  );
});

// projects/testers/routes-lit/entry.client.ts
import { initClient } from "@hwy-js/client";
import { HwyRootOutlet } from "@hwy-js/lit";
import { html, render } from "lit";
import { Sidebar } from "./components/sidebar";

await initClient(() => {
  render(
    html`
      ${Sidebar({})}
      <main>
        ${HwyRootOutlet({
          fallbackErrorBoundary: () => html`<div>Error Boundary in Root</div>`,
        })}
      </main>
    `,
    document.getElementById("root") as HTMLElement,
  );
});
