// packages/react/src/recursive.tsx
import { startTransition, useEffect, useMemo, useState } from "react";
import {
  AdHocData,
  HWY_ROUTE_CHANGE_EVENT_KEY,
  getHwyClientGlobal,
} from "../../common/index.mjs";
import type { GetRouteDataOutput, RouteData } from "../../core/src/router.js";
import { RootLayoutComponent, RootLayoutProps } from "./types.js";

type ErrorBoundaryComp = () => JSX.Element;
type ServerKey = keyof GetRouteDataOutput;
type BaseProps = {
  routeData?: RouteData;
  index?: number;
  fallbackErrorBoundary?: ErrorBoundaryComp;
  adHocData?: AdHocData;
  layout?: RootLayoutComponent;
};

export function RootOutlet(props: BaseProps): JSX.Element {
  const isServer = typeof document === "undefined";
  const ctx: {
    get: (sk: ServerKey) => GetRouteDataOutput[ServerKey];
  } = isServer
    ? {
        get: (sk: ServerKey) => props.routeData?.data?.[sk],
      }
    : (getHwyClientGlobal() as any);
  const idx = props.index ?? 0;
  const CurrentComponent = (ctx.get("activeComponents") as any)?.[idx];
  const adHocData = isServer
    ? props.adHocData
    : getHwyClientGlobal().get("adHocData");
  const [params, setParams] = useState(ctx.get("params") ?? {});
  const [splatSegments, setSplatSegments] = useState(
    ctx.get("splatSegments") ?? [],
  );
  const [loaderData, setLoaderData] = useState(
    (ctx.get("loadersData") as any)?.[idx],
  );
  const [actionData, setActionData] = useState(
    (ctx.get("actionData") as any)?.[idx],
  );
  useEffect(() => {
    window.addEventListener(HWY_ROUTE_CHANGE_EVENT_KEY, () => {
      startTransition(() => {
        setParams(ctx.get("params") ?? {});
        setSplatSegments(ctx.get("splatSegments") ?? []);
        setLoaderData((ctx.get("loadersData") as any)?.[idx]);
        setActionData((ctx.get("actionData") as any)?.[idx]);
      });
    });
  }, []);

  if (!CurrentComponent) {
    return <></>;
  }

  const thisIsAnErrorBoundary = ctx.get("outermostErrorBoundaryIndex") === idx;
  const nextOutletIsAnErrorBoundary =
    ctx.get("outermostErrorBoundaryIndex") === idx + 1;
  const shouldRenderEB =
    thisIsAnErrorBoundary || ctx.get("outermostErrorBoundaryIndex") === -1;

  try {
    if (shouldRenderEB) {
      const EB = useMemo(
        () =>
          (ctx.get("activeErrorBoundaries") as any)?.[idx] ??
          props.fallbackErrorBoundary ?? (
            <div>Error: No error boundary found.</div>
          ),
        [idx],
      );

      if (props.layout && idx === 0) {
        return (
          <props.layout
            adHocData={props.adHocData}
            params={params as any}
            splatSegments={splatSegments as any}
          >
            <EB />
          </props.layout>
        );
      }

      return EB;
    }

    const Outlet = useMemo(() => {
      let Outlet;
      if (!nextOutletIsAnErrorBoundary) {
        Outlet = (localProps: Record<string, any> | undefined) => {
          return <RootOutlet {...localProps} {...props} index={idx + 1} />;
        };
      } else {
        Outlet =
          (ctx.get("activeErrorBoundaries") as any)?.[idx + 1] ??
          props.fallbackErrorBoundary;
        if (!Outlet) {
          Outlet = () => <div>Error: No error boundary found.</div>;
        }
      }
      return Outlet;
    }, [(ctx.get("importURLs") as any)?.[idx + 1]]);

    const extendedProps = useMemo(() => {
      return {
        ...props,
        params: params as any,
        splatSegments: splatSegments as any,
        loaderData,
        actionData,
        Outlet,
        adHocData,
      };
    }, [
      props,
      params,
      splatSegments,
      loaderData,
      actionData,
      Outlet,
      adHocData,
    ]);

    return (
      <MaybeWithLayout {...extendedProps}>
        <CurrentComponent {...extendedProps} />
      </MaybeWithLayout>
    );
  } catch (error) {
    console.error(error);
    return (
      <MaybeWithLayout
        {...props}
        adHocData={props.adHocData}
        params={params as any}
        splatSegments={splatSegments as any}
        children={useMemo(() => {
          return (
            (ctx.get("activeErrorBoundaries") as any)
              ?.splice(0, idx + 1)
              ?.reverse()
              ?.find((x: any) => x) ??
            props.fallbackErrorBoundary ?? (
              <div>Error: No error boundary found.</div>
            )
          );
        }, [idx])}
      />
    );
  }
}

function MaybeWithLayout(
  props: BaseProps & RootLayoutProps & { children: JSX.Element },
): JSX.Element {
  if (props.layout && !props.index) {
    return (
      <props.layout
        adHocData={props.adHocData}
        params={props.params as any}
        splatSegments={props.splatSegments as any}
      >
        {props.children}
      </props.layout>
    );
  }
  return props.children;
}

// packages/npm/lit/src/recursive.ts
import { html, LitElement, TemplateResult } from "lit";
import { property } from "lit/decorators.js";
import {
  getHwyClientGlobal,
  HWY_ROUTE_CHANGE_EVENT_KEY,
  RouteChangeEvent,
  RouteData,
} from "../../common/index.mjs";
import { AsComp, makeComp } from "./utils.js";

type ErrorBoundaryComp = () => TemplateResult;
type BaseProps<AHD extends any = any> = {
  routeData?: RouteData<AHD>;
  index?: number;
  fallbackErrorBoundary?: ErrorBoundaryComp;
  adHocData?: AHD;
  layout?: AsComp<typeof HwyRootLayout<{ adHocData: AHD }>>;
};

const noErrorBoundaryTmpl = html`<div>Error: No error boundary found.</div>`;
const noErrorBoundaryTmplFn = () => noErrorBoundaryTmpl;

let shouldScroll = false;

class HwyRootOutletShadowDef<AHD> extends LitElement {
  @property()
  routeData?: RouteData<AHD>;

  @property()
  index?: number = 0;

  @property()
  fallbackErrorBoundary?: ErrorBoundaryComp;

  @property()
  adHocData?: AHD;

  @property()
  layout?: AsComp<typeof HwyRootLayout>;

  @property()
  passedFromParent?: Record<string, any>;

  private _routeChangeCallback = (e: RouteChangeEvent) => {
    this.requestUpdate();

    if (e.detail.scrollState) {
      shouldScroll = true;
      window.requestAnimationFrame(() => {
        if (shouldScroll) {
          window.scrollTo(e.detail.scrollState!.x, e.detail.scrollState!.y);
          shouldScroll = false;
        }
      });
    }
  };

  connectedCallback(): void {
    super.connectedCallback();
    window.addEventListener(
      HWY_ROUTE_CHANGE_EVENT_KEY,
      this._routeChangeCallback as any,
    );
  }

  disconnectedCallback(): void {
    super.disconnectedCallback();
    window.removeEventListener(
      HWY_ROUTE_CHANGE_EVENT_KEY,
      this._routeChangeCallback as any,
    );
  }

  render() {
    const ctx = getHwyClientGlobal();
    const idx = this.index ?? 0;
    const CurrentComponent = ctx.get("activeComponents")?.[idx];

    const EB = () =>
      ctx.get("activeErrorBoundaries")?.[idx] ??
      this.fallbackErrorBoundary ??
      noErrorBoundaryTmpl;

    let Outlet;

    const nextOutletIsAnErrorBoundary =
      ctx.get("outermostErrorIndex") === idx + 1;

    if (!nextOutletIsAnErrorBoundary) {
      Outlet = (localProps: Record<string, any> | undefined) => {
        const roProps = {
          passedFromParent: localProps,
          routeData: this.routeData,
          fallbackErrorBoundary: this.fallbackErrorBoundary,
          adHocData: this.adHocData,
          index: idx + 1,
        };
        return HwyRootOutlet(roProps);
      };
    } else {
      Outlet =
        ctx.get("activeErrorBoundaries")?.[idx + 1] ??
        this.fallbackErrorBoundary ??
        noErrorBoundaryTmplFn;
    }

    const extendedProps = {
      passedFromParent: this.passedFromParent,
      routeData: this.routeData,
      index: idx,
      fallbackErrorBoundary: this.fallbackErrorBoundary,
      layout: this.layout,
      params: ctx.get("params") ?? {},
      splatSegments: ctx.get("splatSegments") ?? [],
      loaderData: ctx.get("loadersData")?.[idx],
      actionData: ctx.get("actionData")?.[idx],
      Outlet,
      adHocData: ctx.get("adHocData") ?? this.adHocData,
    };

    const ebc = () => {
      return (
        ctx
          .get("activeErrorBoundaries")
          ?.splice(0, idx + 1)
          ?.reverse()
          ?.find((x: any) => x) ??
        this.fallbackErrorBoundary ??
        noErrorBoundaryTmpl
      );
    };

    if (!CurrentComponent) {
      return html``;
    }

    try {
      if (ctx.get("outermostErrorIndex") === idx) {
        if (this.layout && idx === 0) {
          return this.layout({
            adHocData: ctx.get("adHocData") ?? this.adHocData,
            params: ctx.get("params") ?? {},
            splatSegments: ctx.get("splatSegments") ?? [],
            Outlet: EB,
          });
        }

        return EB();
      }

      return MaybeWithLayout({
        ...extendedProps,
        Outlet: (localProps: Record<string, any> | undefined) =>
          CurrentComponent({
            ...extendedProps,
            passedFromParent: localProps,
          }),
      });
    } catch (error) {
      console.error(error);

      return MaybeWithLayout({
        ...extendedProps,
        Outlet: ebc,
      });
    }
  }
}

export const HwyRootOutletShadow = makeComp(
  HwyRootOutletShadowDef,
  "hwy-root-outlet-shadow",
);

class HwyRootOutletDef<AHD> extends HwyRootOutletShadowDef<AHD> {
  createRenderRoot() {
    return this;
  }
}

export const HwyRootOutlet = makeComp(HwyRootOutletDef, "hwy-root-outlet");

function MaybeWithLayout(
  props: BaseProps & HwyRootLayoutProps & { Outlet: Outlet },
): TemplateResult {
  if (props.layout && !props.index) {
    return props.layout(props);
  }
  return props.Outlet();
}

type RoutePropsTypeArg = {
  loaderOutput?: any;
  actionOutput?: any;
  adHocData?: any;
};

type DefaultRouteProps = {
  loaderOutput: any;
  actionOutput: any;
  adHocData: any;
};

type Outlet = (passToChild?: Record<string, any>) => TemplateResult;

export type HwyRouteComponentProps<
  T extends RoutePropsTypeArg = DefaultRouteProps,
> = {
  loaderData: T["loaderOutput"];
  actionData: T["actionOutput"] | undefined;
  Outlet: Outlet;
  params: Record<string, string>;
  splatSegments: Array<string>;
  adHocData: T["adHocData"] | undefined;
};

export type HwyRouteComponent<T extends RoutePropsTypeArg = DefaultRouteProps> =
  (props: HwyRouteComponentProps<T>) => TemplateResult;

export type HwyRootLayoutProps<
  T extends RoutePropsTypeArg = DefaultRouteProps,
> = {
  Outlet: Outlet;
} & Pick<HwyRouteComponentProps<T>, "params" | "splatSegments" | "adHocData">;

export class HwyRouteShadow<
  T extends RoutePropsTypeArg = DefaultRouteProps,
> extends LitElement {
  @property()
  loaderData!: T["loaderOutput"];

  @property()
  actionData?: T["actionOutput"];

  @property()
  Outlet!: (...props: any) => TemplateResult;

  @property()
  params!: Record<string, string>;

  @property()
  splatSegments!: Array<string>;

  @property()
  adHocData?: T["adHocData"];

  @property()
  passedFromParent?: Record<string, any>;
}

export class HwyRoute<
  T extends RoutePropsTypeArg = DefaultRouteProps,
> extends HwyRouteShadow<T> {
  createRenderRoot() {
    return this;
  }
}

export class HwyRootLayoutShadow<
  T extends RoutePropsTypeArg = DefaultRouteProps,
> extends LitElement {
  @property()
  params!: Record<string, string>;

  @property()
  splatSegments!: Array<string>;

  @property()
  adHocData?: T["adHocData"];

  @property()
  Outlet!: Outlet;
}

export class HwyRootLayout<
  T extends RoutePropsTypeArg = DefaultRouteProps,
> extends HwyRootLayoutShadow<T> {
  createRenderRoot() {
    return this;
  }
}
