// typescript/hwy/react/src/link.tsx
import { type ComponentProps, useMemo } from "react";
import { type LinkPropsBase, makeFinalLinkProps } from "../../client/src/impl_helpers.ts";

export function Link(
	props: ComponentProps<"a"> &
		LinkPropsBase<(e: React.MouseEvent<HTMLAnchorElement, MouseEvent>) => void | Promise<void>>,
) {
	const finalLinkProps = useMemo(() => makeFinalLinkProps(props), [props]);

	return (
		<a
			data-external={finalLinkProps.dataExternal}
			{...props}
			onPointerEnter={finalLinkProps.onPointerEnter}
			onFocus={finalLinkProps.onFocus}
			onPointerLeave={finalLinkProps.onPointerLeave}
			onBlur={finalLinkProps.onBlur}
			// biome-ignore lint: this onClick is very intentional
			onClick={finalLinkProps.onClick}
		>
			{props.children}
		</a>
	);
}

// typescript/hwy/solid/src/link.tsx
import { createMemo, type JSX } from "solid-js";
import { type LinkPropsBase, makeFinalLinkProps } from "../../client/src/impl_helpers.ts";

export function Link(
	props: JSX.AnchorHTMLAttributes<HTMLAnchorElement> &
		LinkPropsBase<JSX.CustomEventHandlersCamelCase<HTMLAnchorElement>["onClick"]>,
) {
	const finalLinkProps = createMemo(() => makeFinalLinkProps(props));

	return (
		<a
			data-external={finalLinkProps().dataExternal}
			{...props}
			onPointerEnter={finalLinkProps().onPointerEnter}
			onFocus={finalLinkProps().onFocus}
			onPointerLeave={finalLinkProps().onPointerLeave}
			onBlur={finalLinkProps().onBlur}
			// biome-ignore lint: this onClick is very intentional
			onClick={finalLinkProps().onClick}
		>
			{props.children}
		</a>
	);
}
