// projects/testers/routes-lit/entry.client.ts
import { initClient } from "@hwy-js/client";
import { HwyRootOutlet } from "@hwy-js/lit";
import { html, render } from "lit";
import { Sidebar } from "./components/sidebar";

await initClient(() => {
  render(
    html`
      ${Sidebar({})}
      <main>
        ${HwyRootOutlet({
          fallbackErrorBoundary: () => html`<div>Error Boundary in Root</div>`,
        })}
      </main>
    `,
    document.getElementById("root") as HTMLElement,
  );
});

// projects/testers/routes-react/entry.client.tsx
import { initClient } from "@hwy-js/client";
import { RootOutlet } from "@hwy-js/react";
import React from "react";
import { createRoot } from "react-dom/client";
import { Sidebar } from "./components/sidebar";

await initClient(() => {
	const root = createRoot(document.getElementById("root") as HTMLElement);
	root.render(
		<React.StrictMode>
			<Sidebar />
			<main>
				<RootOutlet
					fallbackErrorBoundary={function ErrorBoundary() {
						return <div>Error Boundary in Root</div>;
					}}
				/>
			</main>
		</React.StrictMode>
	);
});
